#!/bin/sh

toggle_pulse_loopback() {
    if [ -z "$(pactl list modules | grep loopback)" ]; then
        notify-send "PULSE LOOPBACK ON ✅✅✅✅✅" -t 2000
        pacmd load-module module-loopback latency_msec=100
    else
        notify-send "PULSE LOOPBACK OFF ❌❌❌❌❌" -t 2000
        pacmd unload-module module-loopback
    fi
}

toggle_pulse_loopback

