#!/bin/sh

MONITOR_H=1440
MONITOR_W=2560
left_width=$MONITOR_H
mid_x_offset=$left_width
top_x_offset=$(($left_width + $MONITOR_W / 2 + 40))
right_x_offset=$(($left_width + $MONITOR_W))

xrandr --output DP-0.8 --mode 2560x1440 --pos 0x750 --rotate right \
    --output DVI-D-0 --off \
    --output HDMI-0 --mode 2560x1440 --pos ${right_x_offset}x1440 --rotate normal \
    --output DP-0 --off \
    --output DP-1 --off \
    --output DP-2 --mode 2560x1440 --pos ${top_x_offset}x0 --rotate normal \
    --output DP-3 --off \
    --output DP-4 --primary --mode 2560x1440 --pos ${mid_x_offset}x1440 --rotate normal --rate 144 \
    --output DP-5 --off \
    --output DVI-D-1-0 --off \
    --output HDMI-1-0 --off \
    --output HDMI-1-1 --off \
    --output DP-1-0 --off \
    --output DP-1-1 --off \
    --output DP-1-2 --off \
    --output DP-1-3 --off
