CompileFlags:                     # Tweak the parse settings
  Add: [--std=c++20, -stdlib=libc++, -fcoroutines-ts]             # treat all files as C++, enable more warnings
  Compiler: clang++               # Change argv[0] of compile flags to `clang++`

